### ISSUE TITLE
drag and drop models issue

### ISSUE THREAD

**Issue by jahshaka** [jahshaka/Studio#428] opened 2018-08-26 21:16 UTC
when you drag and drop Models into the scene, they always snap to 0 / 0 / 0 and dont go where you put them

when you release the mouse button it always gets added at what looks like 0 / 0 / 0 ie the same place for all drag and drop

**Comment by iKlsR** [comment] 2018-08-27 01:02
Duplicate of #381

**Closed by iKlsR** 2018-08-27 01:02 UTC
