### ISSUE TITLE
loading scene dialog never goes to 100%

### ISSUE THREAD

**Issue by jahshaka** [jahshaka/Studio#422] opened 2018-08-24 12:46 UTC
when i load a scene on windfows, the dialog now goes through the steps of loading - but when it switches to opening the bard shold be at 100% for final step instead it goes back to 0 and white.... really should hit 100% for the last step and stay yhere

**Comment by iKlsR** [comment] 2018-08-27 00:59
As has been said several times this is not a bug. Will be addressed in the upcoming version by #419 .

**Closed by iKlsR** 2018-08-27 00:59 UTC
